[package]
name = "streambewi-esp32"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
streambewi = { path = "../../app" }
iobewi-entry = { git = "https://github.com/iobewi/iobewi", rev = "f0360f51a61c2a475924ab4633b77757b2a832b7", features = ["esp32s3"] }

[build-dependencies]
iobewi-entry-build = { git = "https://github.com/iobewi/iobewi", rev = "f0360f51a61c2a475924ab4633b77757b2a832b7" }

[features]
default = []
usb-debug = ["streambewi/usb-debug"]
