[package]
name = "streambewi-core"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
iobewi-fat16 = { git = "https://github.com/iobewi/iobewi", rev = "ddfa839a15836c3eebedc24fa34efc1d7bd3bc84" }
iobewi-rolling-stream = { git = "https://github.com/iobewi/iobewi", rev = "ddfa839a15836c3eebedc24fa34efc1d7bd3bc84" }
